import { Roboto } from 'next/font/google';
import './globals.css';

const roboto = Roboto({
  subsets: ['latin'],
});

export const metadata = {
  title: 'Book Borrowing Platform',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      data-theme="light"
      className={`${roboto.className} h-full antialiased`}>
      <body className="min-h-full flex flex-col bg-gray-100">{children}</body>
    </html>
  );
}
