import { Roboto } from 'next/font/google';
import './globals.css';
import Navbar from './components/shared/Navbar';
import Footer from './components/shared/Footer';

const roboto = Roboto({
  subsets: ['latin'],
});

export const metadata = {
  title: 'Book Borrowing Platform',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      data-theme="light"
      className={`${roboto.className} h-full antialiased`}>
      <body className="min-h-full flex flex-col">
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
